[build]
  base = "frontend"
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://summer-trip-voting-api.onrender.com"

[[redirects]]
  from = "/api/*"
  to = "https://summer-trip-voting-api.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200